"""auto add likes table

Revision ID: 591a37ded522
Revises: 0e7bb3b416fa
Create Date: 2023-07-05 12:05:00.334678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591a37ded522'
down_revision = '0e7bb3b416fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'story_id')
    )
    op.drop_constraint('users_email_display_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['display_name'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_email_display_name_key', 'users', ['email', 'display_name'])
    op.drop_table('likes')
    # ### end Alembic commands ###
